server:
  port: 8111

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://project1.clzlmjcyxpuf.ap-northeast-2.rds.amazonaws.com:3306/RTS_project
    username: admin
    password: gwang10ju

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      format_sql : true
      ddl-auto: update

#server:
#  port: 8080
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url : jdbc:mysql://localhost:3306/web_project?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: ssafy
#    password: 1234
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      format_sql : true
#      ddl-auto: update